version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "addguid-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vqwlrteupzw2"
s3_prefix = "addguid-aws"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
