AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  addguid-aws

  Sample SAM Template for addguid-aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  AddGuidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: addguid/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Events:
        AddGuid:
          Type: Schedule
          Properties:
            Schedule: cron(7 */3 * * ? *)
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:*' # 本当は s3:PutObjectAcl だけで良い気がしてるんだけど、それだとなぜかAccess Deniedになってしまうので一旦諦めて雑に s3:* にしている
          Resource: "arn:aws:s3:::addguid-aws/*" # https://www.noobs.tokyo/entry/2018/10/15/213237
        - Effect: Allow
          Action:
          - 'dynamodb:Scan'
          Resource: "*" # なんとなく個人的なARNを書きたくなかったので雑に*にしてるけど良くない気がする
  AddGuidAwsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "addguid-aws"

Outputs:
  AddGuidFunction:
    Description: "Add Guid Lambda Function ARN"
    Value: !GetAtt AddGuidFunction.Arn
  AddGuidFunctionIamRole:
    Description: "Implicit IAM Role created for Add Guid function"
    Value: !GetAtt AddGuidFunctionRole.Arn
