AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  addguid-aws

  Sample SAM Template for addguid-aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AddGuidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: addguid/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Events:
        AddGuid:
          Type: Schedule
          Properties:
            Schedule: cron(7 */3 * * ? *)

Outputs:
  AddGuidFunction:
    Description: "Add Guid Lambda Function ARN"
    Value: !GetAtt AddGuidFunction.Arn
  AddGuidFunctionIamRole:
    Description: "Implicit IAM Role created for Add Guid function"
    Value: !GetAtt AddGuidFunctionRole.Arn
